### ISSUE TITLE
Schreibfehler S 25

### ISSUE THREAD

**Issue by captain-o** [allekai/AGD#3]
2.1 Indidzierung 
Ende erster Absatz
Will man nun auf ein Objekt a auf Seite A zugreifen,
so muss die gesamte Seite mit allen ihren enthaltenen **ELementen** mit in den
RAM geladen werden.

Greetings ;)

**Comment by allekai** [comment]
- Abschnitt 2.1:
  **Ein schneller Zugriff auf und eine effektive Verarbeitung der** Daten ist jedoch...
  Das unterstrichene nicht in ein **nicht** umwandeln
- Abschnitt 2.2.1:
  Ähnlichkeit von zwei Daten**punkten**
  Die erste Normalisierung nochmal neu formulieren. v_i ist irgendein Wert eines Tupels. Normalisiert wird dieser mit v_j, einem anderen Wert aus dem selben Wertebereich. Es wird das Minimum und das Maximum aus dem jeweiligen Wertebereich genommen. Bsp: Alter aus [0, 100], dann min v_j = 0 und max v_j = 100.
- Abschnitt 2.2.2:
  **wiederhole** das Ganze
  der Raum, den man abfragt**,** eine Überlappung
  Fall**s** der Bereich
  Hinweis hinzufügen, dass man wissen sollte, wie die einzelnen Schritte der NN-Anfrage ablaufen.
- Abschnitt 2.2.3:
  Erläutern, was mit nicht regelmäßigen Objekten gemeint ist (alles, was nicht rechteckig oder sonst wie einfach beschreibbar ist)
  Leerzeichen bei Positionsbeschreibung
  kein Komma vor als
  Verweis auf die Vorlesung bzgl. Traversierung eines potentiellen Indexbaumes
- Abschnitt 2.2.4:
  Logische Knoten sind die Knoten eines **Indexbaumes.**
  Tabelle please. Wtf.
- Abschnitt 2.2.5:
  Auflistung eklig auseinandergerissen. Abb. 10 lässt das komisch aussehen. 
  Kommata beim Schlusswort
- Abschnitt 2.3:
  Kleines Schlusswort zum Kapitel
